### ISSUE TITLE
fix blog post

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#100]
@NyakudyaA where is the code you refer to in this post? http://mezzanine.kartoza.com/en/admin/blog/blogpost/113/

Please add it, I though the import from WP had not pulled it in but it looks like it's missing from WP as well.

**Comment by gubuntu** [comment]
@NyakudyaA do you remember which post this refers to, since that link is no longer active?

If so, did you fix it? If not you could look through draft and published posts on our current blog and fix it else close this.

**Comment by NyakudyaA** [comment]
@gubuntu I think it was the mass reprojection of H5 files which I have included the code in the blog

**Comment by gubuntu** [comment]
OK if it was that one, I've fixed the code formatting
