### ISSUE TITLE
integrate Mailchimp

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#107]
We have some Mailchimp lists, website visitors should be able to subscribe to these. Put near the other Kartoza presence icons (#106)

Gavin to add Mailchimp details...

subscribe to mailing list (our Mailchimp lists)
- Kartoza News
- Training
- all

new blog posts get posted to Kartoza News (automatically)

New courses and other content get posted to the appropriate list manually. 

consider https://bitbucket.org/naritas/mezzanine-mailchimp

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#16

**Comment by carina1000** [comment]
@gubuntu unfortunately insighly and mailchimp don't have integration options so new contacts need to be added manually

**Comment by gubuntu** [comment]
@carina1000 this issue was closed and moved to kartoza/kartoza.com#16, please comment there
