### ISSUE TITLE
integrate payment gateway(s)

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#114]

**Comment by cchristelis** [comment]
Let's try and integrate EFT payments. As they don't incur costs.

**Comment by gubuntu** [comment]
1. First option before we have any payment gateways implemented
   - Payment defaults to a page explaining the manual payment process: our bank account details, who to contact, what reference to use etc. and still allows admin to mark a payment as complete. 
   - This == @cchristelis EFT payment?
2. List of payment options to implement
   1. Paypal: Gavin has official Kartoza paypal account. There are various ways to integrate. This will cover any foreign payments. As simple as http://cartridge.jupo.org/integration.html#payment
   2. A South African payment gateway since most clients and courses will be in SA
      1. I propose SagePay because we're already using Pastel online. 
   3. If @cchristelis meant SID by EFT then a service (setcom) that implements that (low priority)

## Resources
- http://cartridge.jupo.org/index.html
- http://www.theforge.co.za/2012/06/13/south-african-payment-gateways-that-dont-require-bank-registration/
- https://www.maxxor.com/blog/payment-processing-for-south-african-e-commerce-websites/

**Comment by cchristelis** [comment]
@gubuntu, yeah I think 1 is a good minimal solution, which won't require any fees...

**Comment by gubuntu** [comment]
@meomancer please get item 1. from https://github.com/kartoza/docker-mezzanine/issues/114#issuecomment-244975530 in place before Friday so we can use the shop.
