### ISSUE TITLE
admin is not sizing properly to my screen

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#115]
it's extending past the right edge - if it's doing that for you please fix, if not then it might be something my side. There's also no horizontal scroll so it's very difficult to work in. 

e.g. http://mezzanine.kartoza.com/en/admin/shop/product/1/

**Comment by timlinux** [comment]
Does the same for me

**Comment by gubuntu** [comment]
@Christiaanvdm why is this in progress? are you actually working on it? Expect to fix it soon?

**Comment by gubuntu** [comment]
this is in the Ready column, does that mean you're doing it this sprint?
