### ISSUE TITLE
gallery upload style needs fixing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#118]
![screenshot from 2016-09-03 21-35-33](https://cloud.githubusercontent.com/assets/496911/18227259/813d75a8-721e-11e6-84b3-240cf9b02d9f.png)

**Comment by timlinux** [comment]
![screen shot 2016-09-15 at 2 05 24 pm](https://cloud.githubusercontent.com/assets/178003/18549225/7d6cfd1c-7b4d-11e6-8901-f088fe589f76.jpg)

This is already sorted out as per above screen
