### ISSUE TITLE
for logged in staff, differentiate draft items

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#127]
Draft Blogs and Posts appear as 'Published' to logged in staff.

This is a nice feature but staff need some way of seeing which are published and which are draft. Perhaps a different title font or colour for draft items?

**Comment by meomancer** [comment]
it is already in list of blog

and admin could multiple select that radio button and click save button to publish it (or make as a draft again)

![selection_006](https://cloud.githubusercontent.com/assets/4530905/18268570/92c50ef8-744e-11e6-8c32-fc5f71050d8d.png)

**Comment by gubuntu** [comment]
Yes @meomancer :-)  but I'm talking about when you view the site, not in admin. 

Also, please don't work on backlog issues (see waffle view)

**Comment by timlinux** [comment]
See #147 - I would rather we hide unpublished items for both logged in and normal users. Otherwise we have the situation when a client is standing next to us and we are showing them something on the site that they see all the half-assed stuff we have too...

**Comment by gubuntu** [comment]
then we could just logout? We still need to be able to preview unpublished content.

**Comment by timlinux** [comment]
I think you will still be able to preview things - just click the 'view on site' link. This is similar to how wp handles it - it doesn't show draft articles and items in the UI unless you explicitly ask for them.

**Comment by gubuntu** [comment]
n/a to ERPNext
