### ISSUE TITLE
Tidy up team member page

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#138]
Please see image below for suggested improvements:

![screen shot 2016-09-12 at 4 48 58 pm](https://cloud.githubusercontent.com/assets/178003/18440369/21ebfdd0-7909-11e6-9da2-09c0645194c8.jpg)

**Comment by timlinux** [comment]
Looks like the white space between image and name is already sorted - just the header to fix please

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#15
