### ISSUE TITLE
Include legends in leaflet WMS client

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#139]
Probably this ticket could go in the django-wms repo but I will file it here to keep everything in one place.

Please add support for auomatically generating a legend for the maps we publish. For reference see map old content at http://maps.kartoza,com
Example usage:

```
        <script src="../js/leaflet.js"></script>
        <script src="../js/leaflet.zoomdisplay.js"></script>
    <script>
        var map = L.map('map', {
                center: [-34.02205, 20.44254],
                    zoom: 15,
                    minZoom: 14,
                    maxZoom: 18,
                    maxBounds: [[-34.049,20.410] ,[-34.010,20.478]],
        });
        var qgis = L.tileLayer.wms("http://maps.kartoza.com/cgi-bin/qgis_mapserv.fcgi?map=/web/Swellendam/Swellendam.qgs", {
            layers: 'Swellendam',
            format: 'image/png',
            transparent: true,
            attribution: '(c)<a href="http://osm.org/copyright">OpenStreetMap</a> contributors and <a href="http://www.ngi.gov.za/">SA-NGI</a>'
        }).addTo(map);
        uri = "http://maps.kartoza.com/cgi-bin/qgis_mapserv.fcgi?map=/web/Swellendam/Swellendam.qgs&&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetLegendGraphic&FORMAT=image/jpeg&LAYER=Swellendam&STYLE=";
        L.wmsLegend(uri);

```

**Comment by meomancer** [comment]
Django wms client upstream is updated:
https://github.com/meomancer/django-wms-client/commit/a868558752a91a03024440b5c6aa7dc5ea4737c4

fixs :
- add attribution field
- add center of map field that can be filled manually (if not, it will be calculated)
- fixed map is not shown
- add wms legend

![screenshot from 2016-11-17 16 05 03](https://cloud.githubusercontent.com/assets/4530905/20382808/fadb4f2e-acdf-11e6-8ca0-390f64b091f5.png)
![screenshot from 2016-11-17 16 05 05](https://cloud.githubusercontent.com/assets/4530905/20382809/fadf12f8-acdf-11e6-9104-7b63383c10f1.png)
![screenshot from 2016-11-17 16 04 49](https://cloud.githubusercontent.com/assets/4530905/20382812/fbe8c2ca-acdf-11e6-9587-0d3ef4457eff.png)

need to redeploy with disabled cacher

**Comment by timlinux** [comment]
Nice thanks @meomancer !

Can you merge your changes to the upstream kartoza/django-wms-client repo and deploy your fixes on kartoza.com?

**Comment by meomancer** [comment]
done
http://kartoza.com/en/map/swellendam/
http://kartoza.com/en/map/boosmansbos/
