### ISSUE TITLE
product options not filtering properly

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#148]
When you view a product page (e.g http://kartoza.com/en/shop/product/geospatial-data-in-postgis-1/), only the available product options should be selectable. These are controlled by a combination of the 
- product filter in http://kartoza.com/en/admin/pages/page/9/
- and the current variations in http://kartoza.com/en/admin/shop/product/3/ (which in turn depend on product options: http://kartoza.com/en/admin/shop/productoption/) 

If you choose an available date for a product, then it should filter on the venue that matches that date, but it is not doing so. Please investigate and fix. 

Each field should also be sorted. (split to #227)

I have set these up carefully and the shop is in production so please be careful.

**Comment by gubuntu** [comment]
It does tell you an option is unavailable after you click 'Buy' but it would be better if it filtered the dropdowns during product selection, otherwise it's a hit and miss process.

**Comment by christodewit** [comment]
Hi @rischanlab I was adding course dates on the Kartoza webiste.
I noticed that when displayed on the website these dates are mixed up. 
Is there a way to reorganize these dates to display in chronological order?

**Comment by gubuntu** [comment]
@rischanlab please attend to this asap. If you're not going to get it done before you leave then please assign to @dimasciput

**Comment by rischanlab** [comment]
Hi @gubuntu it seems that I am not able to plot time for this issue. I will assign it to @dimasciput

**Comment by christodewit** [comment]
This issue has become urgent as clients get irritated

**Comment by gubuntu** [comment]
@boney-bun do you have docker-mezzanine dev env set up for kartoza.com yet?

**Comment by christodewit** [comment]
This issue has become very urgent:

As a result we have clients booking for courses at the wrong venue.

![screen shot 2018-02-14 at 13 05 36](https://user-images.githubusercontent.com/25034035/36201175-ca0669a2-1187-11e8-8cc2-7e0e50153023.png)

**Comment by gubuntu** [comment]
@boney-bun please deploy to production by tomorrow.

**Comment by boney-bun** [comment]
hi @gubuntu @christodewit the fix for this issue is on the production now.

**Comment by gubuntu** [comment]
thanks @boney-bun. Did you merge develop with master and tag a release before deploying?

**Comment by gubuntu** [comment]
@christodewit as per https://github.com/kartoza/docker-mezzanine/issues/148#issuecomment-247780149 I don't understand how anyone could have booked for an invalid event. When I tested it then, if you tried the wrong combination there would be an error. So it was an irritation but would not result in an \impossible' booking. 

Please test the behaviour now and close if you are happy

**Comment by christodewit** [comment]
@gubuntu The site is filtering the course dates with the course venues. 👍
