### ISSUE TITLE
Please review and add announcements app

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#15]
https://github.com/joshcartme/mezzanine-modal-announcements

See if it works well first

FYI @gubuntu - we can use this to alert users to a new course etc.

**Comment by meomancer** [comment]
@timlinux 
It seems that this library uses django 1.7 and before. There is error in it's modelForm

```
File "/usr/local/lib/python2.7/site-packages/django/forms/models.py", line 230, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form SiteAnnouncementModelForm needs updating.
```

what do you think @timlinux ? should we just carry all of it's library so we could change to 1.8?
