### ISSUE TITLE
Please use kartoza.com for calendar invites

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#158]
Gav our training calendar shows invites to fossgisacademy - can you update this to kartoza.com:

![screen shot 2016-09-19 at 10 41 55 pm](https://cloud.githubusercontent.com/assets/178003/18648322/6b1d19d8-7eba-11e6-9563-f2fed1b5e7b1.jpg)

**Comment by gubuntu** [comment]
@christodewit please check that all upcoming Kartoza training calendar entries do NOT have a conferencing option enabled. You have to do this in the web client. 

@timlinux to change the domain we'd have to remove this calendar and create a new one which I'd rather not do now, so removing the conferencing option will remove the Hangout link.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza#449
