### ISSUE TITLE
Please move the training calendar out of top menu

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#159]
Its redundant there as it is already in the training page and its a waste of space in the menu - lets keep it clean and tight rather....

![screen shot 2016-09-19 at 10 44 27 pm](https://cloud.githubusercontent.com/assets/178003/18648383/af85df4c-7eba-11e6-9396-153e2e7573c0.jpg)

**Comment by gubuntu** [comment]
done, wasn't supposed to go there in the first place.
