### ISSUE TITLE
Please get mcedit working for rich text posts in admin

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#16]
See for example the about page content I was trying to port over

**Comment by meomancer** [comment]
hello @timlinux 
is it something like this?

![screenshot from 2016-08-15 15 38 28](https://cloud.githubusercontent.com/assets/4530905/17659672/5e5102d2-62fe-11e6-9036-8743251e0a85.png)

**Comment by timlinux** [comment]
Perfect!
