### ISSUE TITLE
add admin option to skip shipping address

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#163]
A training course is a product that does not get shipped so we should have the option in Product admin to make shipping address optional or even remove it from the order process for that product.

**Comment by meomancer** [comment]
@gubuntu 
i got a problem with this approach
when we flag to skip shipping address for each of product, but when user make cart with combination
(product A is shipped and product B is not)

how we manage it?

My solutions:
1. Just make global setting that our all product doesn't need shipping address
2. This is unconfortable, which is when user already choose non shipped product, they can't choose shipped product (just give description when "buy" button is hovered)
3. Let it go~ when shipped product in cart as well as unshipped product, shipping address is still needed
