### ISSUE TITLE
We need a kartoza theme

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#17]
Probably we want this in a separate repo, but for now lets just set it up as part of this repo, we can hive it off later....

I think we need to drop the dark banner of the old site and rather go with a light, clean banner...

It would be good to keep the basic elements of the currently deployed theme and just adapt it to our branding etc.

**Comment by timlinux** [comment]
#cc @gubuntu

**Comment by dimasciput** [comment]
Updated https://github.com/kartoza/docker-mezzanine/pull/23
