### ISSUE TITLE
error on uploading proof of payment

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#170]
The client on order ID 7 tried to confirm payment but 'got an error message' 

Please fix and confirm all aspects of confirmations work.

**Comment by gubuntu** [comment]
@rischanlab could you try to tackle this? It is urgent.

**Comment by meomancer** [comment]
Hi @gubuntu 
I'm sorry i haven't seen this ticket
fixed it
the error because payment's migrations wasn't migrated 

Now we can make proof of payment and also fix bug that file is not uploaded (release version 1.1.1)

**Comment by gubuntu** [comment]
thanks @meomancer
