### ISSUE TITLE
Selecting headings on new pages

### ISSUE THREAD

**Issue by christodewit** [kartoza/docker-mezzanine#184]
# Problem

When I try to change the selected text into a headings format it changes the all text into the selected heading.

# Proposed solution

To only change the selected text into the headings format

**Comment by gubuntu** [comment]
It's not a bug, you probably pasted it straight from the email so it has all the email html formatting. You need to clear all formatting first either in place or by pasting into a text editor (NOT word processor) then copying and pasting again into Django so you have raw text. Then all the formatting will work as expected.

**Comment by christodewit** [comment]
The same thing happens on other pages that I have not created myself.
