### ISSUE TITLE
Layout in small screen is not good

### ISSUE THREAD

**Issue by meomancer** [kartoza/docker-mezzanine#185]
# Problem
On small screen, the layout is not good

![selection_001](https://cloud.githubusercontent.com/assets/4530905/22643558/9d40c596-ec91-11e6-9639-3e27c46a0eed.png)
![selection_002](https://cloud.githubusercontent.com/assets/4530905/22643559/9d476590-ec91-11e6-9440-788f3e25b1cf.png)

# Solution
Relayouting on small screen

**Comment by gubuntu** [comment]
covered by https://github.com/kartoza/kartoza.com/issues/63
