### ISSUE TITLE
validation on Billing details checkout page not working in Firefox

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#190]
worked in Safari

not working in Firefox 52 (on Mac)

incorrect phone number validates correctly. 

Missing required fields shows a popup 'please match the requested format' pointing to the top of the screen instead of highlighting the invalid fields with a specific message, such as 'required'

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#7

**Comment by dimasciput** [comment]
@Christiaanvdm please test this and try to fix it
