### ISSUE TITLE
Replacing a zip files for plugin with same version causes install error.

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-mezzanine#194]
# Problem

When trying to replace a zip file in the plugin repository it causes errors on install in QGIS. 

To replicate
* Publish a plugin and give it a version number ie 2.0. Go to QGIS and it works.
* The uploaded zip file is parcel_plugin.zip
* I commit other files to a git branch and zip that branch as parcel_plugin.zip. This needs to be published as version 2.0 again.
* Go to kartoza plugin repo and update the current zip file with the new one. 
* The new zip file you have just updated is now being called parcel_plugin_xhshdh.zip
* Go to QGIS and install the plugin and nothing works.

# Solution
* I think when you replace the zip file for the same version the replace is not being handled properly and might be keeping references to the old zip file.
* Check to see if there is logic to handle replacing a zip file with one with the same name.
* When I replace parcel_plugin.zip with a zip file using a different name it works perfectly

**Comment by NyakudyaA** [comment]
comment from @gubuntu  related comment: surely the zip file should have the same name as the GitHub repo base directory?

**Comment by dimasciput** [comment]
@NyakudyaA I have fixed this, can you test it on kartoza site again?

**Comment by NyakudyaA** [comment]
thanks, @dimasciput  will try it when I need to change the plugin

**Comment by gubuntu** [comment]
@NyakudyaA please comment or close if fixed

**Comment by dimasciput** [comment]
@Christiaanvdm please test this issue, if it looks fine then close this ticket

**Comment by Christiaanvdm** [comment]
Proof of it working:

![GIF101](https://user-images.githubusercontent.com/34506346/62113679-4bad8b00-b2b5-11e9-8afc-89ff0d8dc72e.gif)
