### ISSUE TITLE
add project showcase app to website

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#200]
We need a company resource to capture project details for
1. company records
1. showcase elements on the website
   1. full project portfolio
   1. 'suppliers to' or ''partners' or 'we power...' sections
   1. etc
1. generate portfolio pdfs
   1. Kartoza brochure
   1. World Bank proposal format

# Fields - as structured as possible
- client details incl logo
- project details
- screenshots, photos, etc.
- references

**Comment by carina1000** [comment]
Hi @gavin could we perhaps have a call to talk about this??

**Comment by gubuntu** [comment]
@Christiaanvdm the 'references' here refer to references or testimonials from clients. So it should be a rich text field linked to a contact at a client and allow for more than one.
