### ISSUE TITLE
Client Logos Update

### ISSUE THREAD

**Issue by christodewit** [kartoza/docker-mezzanine#207]
_From @cchristelis on September 27, 2017 12:37_

# Problem

Our client logos aren't up to date.

# Proposed Solution

Please add the logos.

_Copied from original issue: kartoza/kartoza#442_

**Comment by christodewit** [comment]
_From @gubuntu on September 27, 2017 14:53_

which logos specifically, and where do they need to be updated (path, web page)?

**Comment by christodewit** [comment]
Petra found out from Christian that our client's logos are not updated on our website.

**Comment by christodewit** [comment]
_From @gubuntu on October 15, 2017 12:26_

Can you do this @christodewit?

**Comment by christodewit** [comment]
The following list of clients are not represented on our website:
AgriTechnovation
Asem Running
Cadasta
Cyanolakes
HOT
MySmartFarm
SwiftGeospatial
SpatialMatrix
GCXWater
ITHACA
African Urban Solutions foundation
ExperiCo
University of Denmark
University of Venda (Department of Zoology)
UWC Institute for Post-School Studies (IPSS)
May I add all these to the website?

**Comment by gubuntu** [comment]
This is the list:

DFAT
World Bank
AgriTechnovation
iMMAP
SANSA
Humanitarian OpenStreetMap Team (HOT)
Tracks4Africa
Cyanolakes
CSIR
UWC Institute for Post-School Studies (IPSS)
MySmartFarm
Kirchhoff Surveyors
i@ Consulting
RHDHV
ITHACA
Further Education and Training (FET) Institute
University of Venda
TPA consulting
1Map
Terrestris
QGIS.ORG
Saab Grintek Defence
Cross Cultural Consulting Services
GIS solutions
Metaspatial
University of Fort Hare
Violence Prevention Through Urban Upgrading
Webtide
Freshwater Resource Centre
SpatialMatrix
NGI
Overberg FPA
University of Denmark
University of Pretoria CE
Cape Town Marathon
AfriGIS
SwiftUASGeospatial
Skybird
Groundtruth
BMI Tech Knowledge
Leo Consult
FNB

**Comment by christodewit** [comment]
@gubuntu Can I start collecting the above-mentioned client logos to add to our website?

**Comment by gubuntu** [comment]
yes, no need to ask. 

Just ensure they are sufficient size and resolution.

**Comment by gubuntu** [comment]
looking fairly good so far but quite a few are missing and they are not a consistent size. For the very small ones maybe you need to clip away some white border. 

Also in general you should ask the person who created an issue to review it and let them close it.

**Comment by gubuntu** [comment]
also if you can, order the images according to my list.

**Comment by christodewit** [comment]
Will do so

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#6
