### ISSUE TITLE
Add Adwords Tags to our sites

### ISSUE THREAD

**Issue by carina1000** [kartoza/docker-mezzanine#214]
# Problem: 

We need to to track conversions (sign-ups) on google adwords we need to add the global site tag and event snippet tag onto our website.  

# Solution:

- [x] Check if global site (on every page of our website) is the same - if not, update it: 

<script async src="https://www.googletagmanager.com/gtag/js?id=AW-1001220779"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-1001220779');
</script>

- [x] Add event snippet on /Your Cart page and /Your Wishlist page:

<script>
  gtag('event', 'conversion', {
      'send_to': 'AW-1001220779/aa93CLX6uwMQq9W13QM',
      'value': 1.0,
      'currency': 'ZAR'
  });
</script>

**Comment by boney-bun** [comment]
@gubuntu @carina1000
i found this old code on our footer:
```
<script>
{% if settings.GOOGLE_ANALYTICS_ID and not request.user.is_staff %}

var _gaq = _gaq || [['_trackPageview']];
_gaq.unshift(['_setAccount', '{{ settings.GOOGLE_ANALYTICS_ID }}']);
(function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = '//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
})(document, 'script');
{% endif %}

</script>
```
should i update the code based on this article: https://developers.google.com/analytics/devguides/collection/upgrade/
or, just keep it the way it is now?

**Comment by gubuntu** [comment]
@boney-bun why are you commenting here? This issue is closed. The discussion is now in https://github.com/kartoza/kartoza.com/issues/32
