### ISSUE TITLE
Not receiving emails

### ISSUE THREAD

**Issue by christodewit** [kartoza/docker-mezzanine#215]
**Problem**

Petra and I are not receiving emails from 
* info@kartoza.com
* info@kartoza.co.za

@gubuntu @boney-bun

**Comment by gubuntu** [comment]
@christodewit does this have anything to do with the website? If not rather move to kartoza or admin repo.

**Comment by gubuntu** [comment]
info@kartoza.com was at one stage an alias of Petra's but it not atm, not sure why or how. 

Who should it be going to? If it's one person I'll make it an alias. If it's more that one I'll make it a group.

**Comment by christodewit** [comment]
Petra received mail saying that the address could not be found.

We have been experiencing problems regarding the emails. 
From the website such as not receiving the orders coming through.

![screen shot 2018-02-19 at 12 56 47](https://user-images.githubusercontent.com/25034035/36374561-63cb1d36-1574-11e8-8d14-c20ecc689295.png)

I did a few test emails now to info@kartoza.com and it went through correctly.

**Comment by gubuntu** [comment]
info@kartoza.com is an alias of admin@kartoza.com which is a group containing @christodewit and @petrapaton.

website orders is a different issue https://github.com/kartoza/kartoza.com/issues/31

**Comment by christodewit** [comment]
@gubuntu @cchristelis @timlinux Petra and I are not receiving Email notifications for new course applications.

**Comment by gubuntu** [comment]
@christodewit please rather create a new issue and assign as a bug to @boney-bun, no need to notify all directors.

**Comment by christodewit** [comment]
@gubuntu Thanks.
