### ISSUE TITLE
course fields should be sorted

### ISSUE THREAD

**Issue by boney-bun** [kartoza/docker-mezzanine#216]
## Problem
product dropdown fields are not sorted

## Solution
product fields must be sorted 
- words (in the case of courses, place names) ascending alphabetic
- dates ascending

**Comment by gubuntu** [comment]
@boney is this fixed as amended? Which PR fixed it?

**Comment by boney-bun** [comment]
just remembered that you asked to be on kartoza.com instead.
i've made the same issue here: kartoza/kartoza.com#33.
so i closed this ticket.

**Comment by gubuntu** [comment]
no, it should be here. It is a generic cartridge improvement, not specific to kartoza.com
