### ISSUE TITLE
VAT Increase on Scheduled Courses

### ISSUE THREAD

**Issue by christodewit** [kartoza/docker-mezzanine#237]
_From @christodewit on April 6, 2018 12:26_

# Problem
Incorrect VAT displayed on the website

# Solution
Increase the VAT to 15% as per SA VAT Increase

@ann26 @sonlinux @gubuntu 

_Copied from original issue: kartoza/Admin#215_

**Comment by meomancer** [comment]
Purposes:
- add "current vat" on the admin mezzanine, so we could change it in admin
site
- maybe we can linked vat value to the payment, so if someone want to
download or checking their old payment, the vat that show is old vat one
(we need to add data migrations in the process)

**Comment by cchristelis** [comment]
Hi @meomancer and @boney-bun, since this is in place since the first of this April. This has become a very urgent issue.

**Comment by boney-bun** [comment]
@cchristelis @meomancer i've made a PR on #240 
example of the PR after a user clicked on `Buy` button:

![screen shot 2018-04-11 at 11 24 50 pm](https://user-images.githubusercontent.com/4602383/38630087-17b0d38e-3de0-11e8-9990-b925a84a4ae7.png)

When the user clicked on `Return to Checkout`:
![screen shot 2018-04-11 at 11 25 09 pm](https://user-images.githubusercontent.com/4602383/38630110-292daf10-3de0-11e8-8462-5875eb64399c.png)

Please note this PR is for the frontend.
@cchristelis @christodewit Do you also would like to add it on the admin page as suggested by @meomancer ?

**Comment by boney-bun** [comment]
Now, we can change the VAT from admin page (note: need to reload the server).
Thanks to @meomancer for the tips.

The PR in action:
![newvat](https://user-images.githubusercontent.com/4602383/38880929-10add360-4291-11e8-860e-d808d5ea7e9b.gif)
