### ISSUE TITLE
We need to integrate a twitter feed block on the front page

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#33]
Maybe next to the blog feed block (see #31 ) we can have a twitter feed. We can set it up to show any recent tweets from Gav or me I guess...? Or maybe mentions of Kartoza? What do you think @gubuntu ?

See also http://mezzanine.jupo.org/docs/twitter-integration.html

Note that if we use cron it should run in a separate container. Otherwise consider celery-beat (maybe @lucernae can pick up this ticket if needed as he has used beat a lot). Also please enable twitter posting when publishing a new blog post (also explained in the page above).

**Comment by gubuntu** [comment]
Nice work so far @meomancer 

And @timlinux I do like the idea. We should be able to register any twitter account or tag to follow as well as any twitter account to post as

**Comment by timlinux** [comment]
How do we actually manage the twitter stuff @meomancer ? I see it in the permission groups, but no admin pages for it?

**Comment by meomancer** [comment]
@timlinux 
you could set it in : http://kartoza.co.za/en/admin/conf/setting/
there is twitter section
