### ISSUE TITLE
We need to fix the permalink so that blog articles in the new site will still be found.

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#34]

**Comment by dimasciput** [comment]
@timlinux Could you elaborate more about this issue? Currently link to a blog post will look like this 
http://mezzanine.kartoza.com/blog/how-to-quickly-transform-a-bounding-box-from-one-crs-to-another-using-qgis/

**Comment by cchristelis** [comment]
@timlinux, we are not quite sure what you mean here. Could you please add a short description.

**Comment by timlinux** [comment]
So if you go to an article on the current website e.g.:

http://kartoza.com/qgis-desktop-in-docker/

Then look at the url layout for the same article on the new site:

http://mezzanine.kartoza.com/blog/running-qgis-desktop-in-a-docker-container/

Search engines have already indexed the site on the wp url scheme, so when we switch to the mezzanine site, we are going to have a bunch of broken links....

**Comment by cchristelis** [comment]
This can already be done at http://mezzanine.kartoza.com/en/admin/redirects/redirect/add/.

**Comment by cchristelis** [comment]
I'm adding the middleware to avoid the redirect happening after the url has been resolved by the app...
