### ISSUE TITLE
Unable to select a person photo in file browser

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#37]
![globe](https://cloud.githubusercontent.com/assets/178003/17874855/90eb06d6-68ce-11e6-8795-325d03b5b4d0.gif)

In Safari it is even worse since I do not get a select box....

**Comment by meomancer** [comment]
hello @timlinux 
on the mezzanine.kartoza, it was not latest project

i pulled it this morning, with the fix
https://github.com/kartoza/docker-mezzanine/pull/29

but it is hacked fix

**Comment by cchristelis** [comment]
This is working now.
