### ISSUE TITLE
Make admin work nicely with Safari

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#41]
E..g uploading images and then assigning them to an article is not working.... Please have a general test around and resolve any issues...

**Comment by cchristelis** [comment]
@timlinux, please review this ticket in light of recent release and close, or list the specific issues you are still having in safari.

**Comment by timlinux** [comment]
Ok I found the root cause: In my user profile I needed to assign myself authoring permissions (I had none assigned):

![screen shot 2016-08-30 at 2 39 47 pm](https://cloud.githubusercontent.com/assets/178003/18089337/c316ed68-6ebf-11e6-91fb-ac18cb02f89a.jpg)

Thanks for looking into this guys. I love how admin looks now, so we got a lot of benefit out of your investigations!
