### ISSUE TITLE
403 on blog admin page

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#42]
http://mezzanine.kartoza.com/en/admin/blog/

![screen shot 2016-08-24 at 10 33 31 pm](https://cloud.githubusercontent.com/assets/178003/17946982/e1b282d8-6a4a-11e6-9120-9abc53eb99c9.png)

**Comment by meomancer** [comment]
duplicates with #46 

it seems that it is restricted by mezzanine itself.
here is from demo
- http://mezzanine.jupo.org/id/admin/blog/
- http://mezzanine.jupo.org/id/admin/pages/
  all gives 403

@timlinux @gubuntu

**Comment by cchristelis** [comment]
Fixed in current release.
