### ISSUE TITLE
Filebrowser not working

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#43]
Guys the fileborwser not working is a real blocker:

![screen shot 2016-08-24 at 11 53 43 pm](https://cloud.githubusercontent.com/assets/178003/17949599/690aaa16-6a56-11e6-97e8-7303143f75cf.png)

Can you replicate this issue? Please try to upload an image then include it in a test post - I don't have any way to do this and it is critical for taking the site online.

Please fix and if needed make an upstream PR to : 
https://github.com/stephenmcd/filebrowser-safe

If needed then update the requirements file to the new version

Please treat as urgent, thanks!
# cc

@gubuntu

**Comment by dimasciput** [comment]
I can't seems to replicate this issue, @meomancer can you try it?

**Comment by meomancer** [comment]
it is already temporary fixed
the error was that "/static/filebrowser/css/filebrowser.css" is not included automatically
and that error is because
```
fileSubmit : function (FileURL) {
        parentWin = (!window.frameElement && window.dialogArguments) || opener || parent || top;
        tinymce = tinyMCE = parentWin.tinymce;
        self.editor = tinymce.EditorManager.activeEditor;
        self.params = self.editor.windowManager.getParams();
        parentWin.document.getElementById(self.params.input).value = FileURL;
        self.editor.windowManager.close(parentWin);
    },
```
tinymce is not defined

guys from fileborwser, is there any library that i miss? because it is not automatically included?
i just fix it temporary by hard set value to mugshot field

**Comment by cchristelis** [comment]
@timlinux, we where able to add this in on some browsers, but the checkbox is still broken.

**Comment by dimasciput** [comment]
I fixed it here : https://github.com/kartoza/docker-mezzanine/pull/49
