### ISSUE TITLE
403 in admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#46]
I get a 403 when I go from http://mezzanine.kartoza.com/en/admin/pages/richtextpage/5/ back to http://mezzanine.kartoza.com/en/admin/pages/ by clicking on the Pages link in breadcrumb path.

**Comment by cchristelis** [comment]
@gubuntu, the first link is now working. The second 'http://mezzanine.kartoza.com/en/admin/pages/' is no longer shown because this is a mezzanine feature.
