### ISSUE TITLE
We need to move images locally and fix urls

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#47]
The blog articles that use images will have image urls pointing to WP e.g.

http://kartoza.com/wp-content/uploads/2015/07/model.png

(see http://mezzanine.kartoza.com/blog/execute-a-processing-model-into-a-plugin/)

We need to systematically fix these either automatically or manually by
- copying the media to mezzanine
  - update the link

**Comment by cchristelis** [comment]
let's fix this manually when we upload articles.

**Comment by gubuntu** [comment]
fixing on import wasn't an option so we need to do this in place.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#12
