### ISSUE TITLE
Modal Broken

### ISSUE THREAD

**Issue by cchristelis** [kartoza/docker-mezzanine#54]
# Problem

When a user selects an image it does not open up in a modal, but rather at the bottom of the page.
# Proposed solution

Fix it.

**Comment by meomancer** [comment]
@cchristelis 
could you try it again? and put screenie?
i couldn't reproduce it

**Comment by cchristelis** [comment]
I can't anymore. It is when I clicked on an image on the latest works. It put the image at the bottom of the page.

**Comment by cchristelis** [comment]
<img width="310" alt="screen shot 2016-09-06 at 10 21 40 am" src="https://cloud.githubusercontent.com/assets/2319504/18266610/c87b98ec-741b-11e6-9ce1-cfe737f60424.png">

**Comment by meomancer** [comment]
@cchristelis 
dimas already fix it in other PR for layouting issue

https://github.com/kartoza/docker-mezzanine/pull/128/files#diff-5469ac2e238b20899aa9a0cead463e6eR260

**Comment by cchristelis** [comment]
@meomancer, in that case let's close this issue!
