### ISSUE TITLE
Add support for file collections

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#64]
See

https://github.com/thibault/mezzanine-file-collections

This will let us host e.g. sample datasets on the web site.

**Comment by cchristelis** [comment]
@meomancer, this seems to be broken at the moment. Please have a look.

**Comment by timlinux** [comment]
I think this or something is still adding South to pip which is breaking migrations. Can you check please?

**Comment by meomancer** [comment]
this close via https://github.com/kartoza/docker-mezzanine/pull/73
