### ISSUE TITLE
Please add Facebook integration

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#68]
Includes the following:

- [ ] click on Like / Follow button on our website 
    - https://github.com/shurik/Mezzanine_Facebook
- [ ] Link FB button to our FB page (add our FB link to the FB button in the footer)
- [ ] post blogs to our FB page automatically (see first comment below)

Gav to supply api details for secret.py

**Comment by gubuntu** [comment]
We want blog posts to automatically post to https://www.facebook.com/kartozaGIS (AppID below)

secret: `f0f0c862e782a6db54e0550b84f1365e`

We can also bring in a FB view to our website with 

```
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1015076958590629',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
```

or add Like, Comment or other buttons https://developers.facebook.com/docs/plugins/

**Comment by rischanlab** [comment]
hi @gubuntu not sure where should I put the like button? 
I tried this. 

![screen shot 2016-11-02 at 7 13 50 am](https://cloud.githubusercontent.com/assets/2235894/19912383/9ff6519a-a0cc-11e6-9160-0d3229d7d2ba.png)

**Comment by gubuntu** [comment]
@rischanlab that position is good - it should appear on each page so a person can like specific pages. 

Please try to wrap these up before you leave. If you don't manage, then assign to @dimasciput

**Comment by rischanlab** [comment]
Hi @gubuntu 
I have a PR for this issue which needs to be merged https://github.com/kartoza/docker-mezzanine/pull/173 

Hi @dimasciput could you please check that PR and  just merge if LGTM 

Thanks

**Comment by christodewit** [comment]
Hi @dimasciput can we link our Facebook page to the website through the social links option?

![social links](https://cloud.githubusercontent.com/assets/25034035/22775414/54a32750-eeb4-11e6-83f5-d45a3d3af8d2.png)

At the bottom of the page? Would like to do the same for Linked in and Twitter.

The other links could be removed?

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#9
