### ISSUE TITLE
Searching for an article gives an error

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#71]
http://localhost:64200/search/?q=test&type=

![screen shot 2016-09-01 at 12 31 00 am](https://cloud.githubusercontent.com/assets/178003/18148672/674e79ca-6fdb-11e6-986e-073f3394df72.jpg)

**Comment by dimasciput** [comment]
@timlinux there is a missing migration file in mezzanine-careers. I added this file in my branch https://github.com/dimasciput/mezzanine-careers. Please update your project, and do migrations again.

**Comment by cchristelis** [comment]
@timlinux, please confirm this and close.

**Comment by timlinux** [comment]
Works now thanks!
