### ISSUE TITLE
Investigate Mezzanine and Django Apps

### ISSUE THREAD

**Issue by cchristelis** [kartoza/docker-mezzanine#77]
# Problem

Mezzanine and Django both have a wealth of libraries to draw from. We would like to have a backlog full of good apps that we could add in future. 
# Proposed solution

Add full descriptions to backlog app tickets. Add new ones. And add comments in this ticket to apps you investigated and did not find interesting.

**Comment by dimasciput** [comment]
Mezzanine third-party plugins list : 
http://mezzanine.jupo.org/docs/overview.html#third-party-plug-ins
