### ISSUE TITLE
add full page gallery view page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#85]
add a page where all images in the slides folder can be browsed and viewed full size

**Comment by gubuntu** [comment]
there is already an Event and Product gallery.  (not to be confused with Mezzanine_events, which are calendar events). Can you publish a Gallery as a page? Please do so for events and products

**Comment by meomancer** [comment]
@gubuntu 
i think this page is already in
https://github.com/kartoza/docker-mezzanine/pull/73

you could just upload image on the page in admin

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#20
