### ISSUE TITLE
We need to make the events list and individual pages beautiful

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#87]
http://mezzanine.kartoza.com/en/events/

![screen shot 2016-09-02 at 10 12 46 am](https://cloud.githubusercontent.com/assets/178003/18197121/ec5a5bb4-70f5-11e6-89d5-1f09d3e189b4.jpg)

http://mezzanine.kartoza.com/en/events/open-gis-and-data-day-cape-town/

![screen shot 2016-09-02 at 10 14 24 am](https://cloud.githubusercontent.com/assets/178003/18197156/1dff53fe-70f6-11e6-8463-0c37ac447133.jpg)

**Comment by gubuntu** [comment]
stale
