### ISSUE TITLE
Add blocks for jobs and events at the bottom of the front page

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#89]
![screen shot 2016-09-02 at 10 25 10 am](https://cloud.githubusercontent.com/assets/178003/18197475/a4126534-70f7-11e6-83e3-037f25a52af3.jpg)

First Jobs, then Events then Blog posts

**Comment by gubuntu** [comment]
This issue was moved to kartoza/kartoza.com#19
