### ISSUE TITLE
Set logos at page bottom of home page for key clients

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#91]
Ideally this should be driven from a gallery so that we can update it in the admin. Each logo should be a clickable link:
# Agritechnovation

http://agritechnovation.com/

![at_logo_colour](https://cloud.githubusercontent.com/assets/178003/18198592/00102ccc-70fd-11e6-8973-c8be19c484eb.png)
# CSIR

http://csir.co.za

![csir-logo](https://cloud.githubusercontent.com/assets/178003/18198676/55db91f0-70fd-11e6-9d67-063914cd9671.jpg)
# Cyanolakes

http://www.cyanolakes.com/

http://cyanolakes.com/wp-content/uploads/2016/06/CyanoLakes_logo.png

Maybe ask @cchristelis if he can get a better version of this
# Tracks4Africa

https://tracks4africa.co.za/

![t4a-logo](https://cloud.githubusercontent.com/assets/178003/18198747/a61e4bbc-70fd-11e6-88a9-3efe458efa60.png)
# FETI

http://www.feti.ac.za/
![feti](https://cloud.githubusercontent.com/assets/178003/18198810/ec347d4c-70fd-11e6-8379-501586573338.jpg)
# DMI

no web site
![logo_dminnovation_round-250x248](https://cloud.githubusercontent.com/assets/178003/18198859/20c4f47e-70fe-11e6-815c-bfb82a3af01c.png)
# SANSA

http://sansa.org.za/
![sansa-logo](https://cloud.githubusercontent.com/assets/178003/18198879/38aa3d6a-70fe-11e6-81d5-6028395c5d6d.png)
# WorldBank/GFDRR

https://www.gfdrr.org/
![gfdrr](https://cloud.githubusercontent.com/assets/178003/18198898/4884f766-70fe-11e6-9860-f0ba235a4581.png)

CC @gubuntu

**Comment by timlinux** [comment]
Please try to standardise the logo dimensions and extend it down into multiple rows if needed....

**Comment by gubuntu** [comment]
or step-scroll across in one row?

and link images to company's website? or to work we did for them? I think the latter.
