### ISSUE TITLE
home page banner size

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#94]
please revert home page banner (carousel) to original height or remove some white space between it and Key Business Areas

**Comment by meomancer** [comment]
@gubuntu 
could you put screenshot? what browser did you try?
in my browser, it is fine

**Comment by cchristelis** [comment]
Half the amount of whitespace between bottom of banner and 'Key business areas'.

**Comment by gubuntu** [comment]
latest Firefox on Ubuntu

![screenshot from 2016-09-06 10-32-49](https://cloud.githubusercontent.com/assets/496911/18266970/5ff255ca-741d-11e6-8454-55e5f55f8e3d.png)

**Comment by cchristelis** [comment]
@gubuntu, I'm moving this out of in progress to ready, since @dimasciput will not have too much time on this this week.

**Comment by cchristelis** [comment]
fixed by #128
