### ISSUE TITLE
enable nesting of pages

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#96]
we should be able to move pages into a tree structure that reflects as sub-menus in the user interface

**Comment by cchristelis** [comment]
@gubuntu, let's reduce the number of items in the menu for now. I suggest we remove:
http://mezzanine.kartoza.com/en/quick-links/
http://mezzanine.kartoza.com/en/showcase/ <-- Move the content to the "Latest Works" section and make a clickable gallery.
http://mezzanine.kartoza.com/en/hosting/
http://mezzanine.kartoza.com/en/events/ <-- Maybe a block on the front page?

**Comment by gubuntu** [comment]
@cchristelis remember if you're logged in Draft items still appear.
- Quick links is Draft but I've moved to footer only
- Showcase is Draft. Where is Latest works? And we want more than a gallery - we'll need text as well. 
- Hosting is Draft
- Events: I've taken out of menu. Ref #89 

But we still need nesting ability.

**Comment by cchristelis** [comment]
@gubuntu, could we leave nesting in the backlog. Although it will be useful in future, it can wait?

**Comment by gubuntu** [comment]
nesting has actually been there all along - just drag pages to the side in admin
