### ISSUE TITLE
develop and document procedure for describing and selling courses

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#98]
How do Mezzanine_events and shop Products integrate?

How can we have a canonical description of a course that then allows an order (registration) and sale of a specific instance (a specific seat on a specific date), and have these displayed on the event calendar and available in the shop, with appropriately summarised information (brief description, CPD points, price, etc)?

@timlinux @cchristelis can you note what you already understand about this here so we know where we stand?

**Comment by timlinux** [comment]
So they don't directly integrate. My plan was to use events for things like meetings, conferences, GIS day etc. (i.e. stuff we don't sell) Then use the store for training courses, support etc (i.e. stuff we sell).

**Comment by gubuntu** [comment]
OK, but then we need an automated way to get saleable courses onto a calendar as if they were events.

**Comment by gubuntu** [comment]
1. Create product category as a Page: Done as "Training Courses"
2. Create a Product in the shop for each course, with a generic / canonical description. This is the course 'abstract class'
3. Create a unique Product Option for each instance of each course. 
   - #111 will adapt this for us
4. Go to the Training Courses page in Admin and ensure the product options that you want are in the Chosen Product Filter, then Save.
5. Go back to the Product and tick the variation(s) you want to add (at the bottom) and Save
6. Go back to the Product and populate Number in stock and Unit price in the new Current Variations lines and Save. 
7. Go to the Product page as a user and you should see the available items for sale.

**Comment by gubuntu** [comment]
Drive: Training/Setting up a scheduled Kartoza training course
