### ISSUE TITLE
Not everything needs to be in the top menu

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#99]
![screen shot 2016-09-02 at 11 16 43 pm](https://cloud.githubusercontent.com/assets/178003/18218523/73882b94-7163-11e6-82a0-0ee2d0135fbf.jpg)

Lets keep things simple and use more context based options e.g. link to feedback form from other training section... Also there are bottom and side menus we could integrate....

**Comment by gubuntu** [comment]
see #96
